version: '3'
services:
  db:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tweets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
  web:
    build: .
    ports:
      - 5000:5000
    command: pipenv run python -u main.py
    depends_on:
      - db
    volumes:
      - .:/code
